function sum() {
    console.log(2 / e);
}

try {
    sum();
} catch {
    console.log("Internal error");
}